// <auto-generated />
namespace PopsAnimalControl_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedEmailAddressToApplicantTable_Mvc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedEmailAddressToApplicantTable_Mvc));
        
        string IMigrationMetadata.Id
        {
            get { return "202109112249287_AddedEmailAddressToApplicantTable_Mvc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
