// <auto-generated />
namespace PAC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Revision1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Revision1));
        
        string IMigrationMetadata.Id
        {
            get { return "202108260744154_Revision1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
